# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone (Optional, e.g., Asia/Kolkata or America/Los_Angeles)
timezone:

# Fill in the protocol & hostname for your site. No trailing slash.
url: "https://dipsova.github.io"
baseurl: ""

title: "Dipsova Saha | Portfolio"
tagline: "AI Technical Writer @ Salesforce"
description: >-
  A technical writing portfolio focused on Salesforce Data Cloud, RAG architectures, and enterprise AI.

github:
  username: dipsova # This hooks up your GitHub profile link

# If you don't use Twitter, you can leave this blank or delete it
twitter:
  username:

social:                                                                                                            
  name: "Dipsova Saha"
  email: write2deepsova@gmail.com                                                                                  
  links:                                                                                                           
    - https://github.com/dipsova-saha                                                                              
    - https://www.linkedin.com/in/dipsova-saha-b1485291/


# Site Verification Settings (Leave empty for now)
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings (Leave empty for now)
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Preferred color scheme setting.
# Keeping it empty automatically defaults to system behavior 
# and provides a beautiful light/dark toggle in the bottom left sidebar.
theme_mode:

# The CDN endpoint for media resources.
cdn:

# The avatar on the sidebar (You can put a local image path here later!)
avatar:

# Social preview image for links shared on LinkedIn/Twitter
social_preview_image:

# Global switch for Table of Contents in posts.
toc: true

comments:
  provider:

# Self-hosted static assets
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
